version: "3.7"
services:
  frontend:
    build: ./frontend/
#    build:
#      context: https://github.com/mialek/FoodTrack.git#:frontend
    image: frontend
#node:13.8.0-slim
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    ports:
      - "80:3000"
    working_dir: /frontend
    environment:
      - CHOKIDAR_USEPOOLING=true
    volumes: 
      - ./frontend:/frontend
#    command: yarn start
    depends_on:
      - backend
    container_name: fdtrck_frontend
    networks: {fdtrck-bridge}


  backend:
#    build: ./
#      context: https://github.com/mialek/FoodTrack.git
    build: ./
    image: backend
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    ports:
      - "5000:5000"
    container_name: fdtrck_backend
    networks: {fdtrck-bridge}
networks:
  fdtrck-bridge:
    driver: bridge
    name: fdtrck_bridge
