version: "2"
services:
  frontend:
    image: foodtrackacr.azurecr.io/frontend
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend
    depends_on:
      - backend

  backend:
    image: foodtrackacr.azurecr.io/backend
    restart: always
    ports:
      - "8080:5000"
