version: "2"
services:
  frontend:
    build: ./frontend/Dockerfile
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  backend:
    build: ./backend/Dockerfile
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./backend:/backend
