version: "2"
services:
  frontend:
    image: ytsejamx/ytsejamx-registry:frontend
    restart: always
    ports:
      - "80:80"
    working_dir: /frontend 

    #  backend:
    #    image: ytsejamx/ytsejamx-registry:backend
    #    restart: always
    #    ports:
    #      - "5000:5000"
    #      - "0:5000"
    #    working_dir: /backend
