export const USER_SIGN_IN = 'USER_SIGN_IN';

export const SET_TIME = 'SET_TIME';
export const PAUSE_RESUME_TIME = 'PAUSE_RESUME_TIME';
export const STOP_TIME = 'STOP_TIME';

export const INCREASE_LOADING = 'INCREASE_LOADING';
export const DECREASE_LOADING = 'DECREASE_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
